### ISSUE TITLE
Support lists of lists

### ISSUE THREAD

**Issue by slyrus** [Symbolics/select#2]
The documentation isn't quite clear on whether lists of lists should be supported (or arbitrary multi-dimensional lists). Sequences and arrays are supported, but should something like this work?

```
(defparameter *foo-list*
  '(("moose" "mouse")
    ("horse" "house")))

(select:select *foo-list*
  (select:range 0 1)
  (select:range 0 1))
```
It seems like it wouldn't be too hard to support this and in at least one case just removing an assertion does allow this to "work". But of this is off-topic, I'll try to find a different approach.

thanks!

**Comment by Symbolics** [comment]
This seems like a reasonable thing to want to do, especially if it's only an assertion getting in the way. I think mostly I was assuming vectors to specify selection, but I'm glad you found another use case.

I'm in the middle of a project at the moment, and won't get around to working on this until early November. If the workaround solves the issue for you, I'll put documentation update, test case and removing the assertion on my to-do list.

**Comment by Symbolics** [comment]
@slyrus, did you find an approach that works for you? If you've got what you need, I think I'm going to update the documentation to say that only vectors and arrays are supported for now, and mention the possibility of using lists of lists as an enhancement.

**Comment by snunez1** [comment]
Closing as stale. @slyrus, if you still need list-of-lists please reopen.
