### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [Symbolics/select#4]
Building with SBCL 2.0.5 / ASDF 3.3.1 for quicklisp dist creation.

Trying to build commit id 6aa66001274d4bbd485059aef6ecbac8d20db499

*select/tests* fails to build with the following error:

```
Unhandled SB-KERNEL:SIMPLE-PACKAGE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1000A10083}>: no symbol named "COLUMN-MAJOR-SETUP" in "SELECT"

```

[Full log here](http://report.quicklisp.org/2021-01-20/failure-report/select.html)

**Comment by Symbolics** [comment]
Fixed

    On Wednesday, January 20, 2021, 7:50:13 PM GMT+8, Zach Beane <notifications@github.com> wrote:  
 
 


Building with SBCL 2.0.5 / ASDF 3.3.1 for quicklisp dist creation.

Trying to build commit id 6aa6600

select/tests fails to build with the following error:
Unhandled SB-KERNEL:SIMPLE-PACKAGE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1000A10083}>: no symbol named "COLUMN-MAJOR-SETUP" in "SELECT"


Full log here
